### ISSUE TITLE
hotkey in obs studio 27.1

### ISSUE THREAD

**Issue by Explicit-Gaming** [snapcrafters/obs-studio#143]
cannot set any hotkey in obs studio on ubuntu 20.04, 20.10, 21.04, 21.10
using any obs studio version over 27.1.
so im forced to run 27.0.1 on my ubuntu machine ( 21.10 right now sicne nothing fix the problem )
tried installing latest version alongside of 27.0.1 ,  but cant set hotkey in 27.1 version.
I NEED HOTKEY thats the whole point.

**Comment by computermacgyver** [comment]
I'm running OBS 27.1.3 installed from snap on Ubuntu 21.10 and experiencing this issue. When I open Settings->Hotkeys, I can click on the think I want to add a hot key for, but then no matter what key combination I try it will not record a hotkey. Nothing happens when pressing a key, and I cannot see any relevant message in the logs

**Comment by Samgarr** [comment]
Same issue here, fresh installation on Ubuntu 21.10.

**Comment by flexiondotorg** [comment]
This is an upstream issue running OBS on Wayland. See this for reference:

  * https://github.com/obsproject/obs-studio/pull/5650

Use a Xorg session to use hotkeys.
