### ISSUE TITLE
Do not copy all of my saved videos in between app updates.

### ISSUE THREAD

**Issue by TZubiri** [snapcrafters/obs-studio#65]
https://github.com/snapcore/snapd/pull/8499

**Comment by popey** [comment]
Save your videos somewhere other than inside the snap versioned folder. The snap has access to the rest of your home directory, and removable media. There's no fixed configuration to save in such a way that causes this to happen. I'd recommend simply changing your default save folder in OBS.

**Comment by TZubiri** [comment]
Thanks for the response.
This must have been a default setting, because I wouldn't have chosen this path. Can we change the default path?

**Comment by TZubiri** [comment]
Will not fix?

**Comment by timthelion** [comment]
This certainly shouldn't have been closed as won't fix. The default is deffinitely to put recorded videos in the snap dir and this is dangerous. Afterall, this means that running `snap uninstall obs-studio` causes total data loss of any recorded videos for anyone who hasn't changed the default directory (happend to me, running ext4magic now to see if I can recover any of the ten hours of screencasts I recorded over the past week).

Turns out that with the current snap config, obs-studio thinks that directory is the `HOME` dir and OBS is configured to place vids in $HOME by default.
 https://github.com/obsproject/obs-studio/blob/076cd5d5d4794dced38676e4ecf8d1fc9d97e692/UI/platform-x11.cpp#L211

**Comment by timthelion** [comment]
`ext4magic` wasn't able to help me here, but it turns out that the data wasn't lost, it was only copied to `/var/lib/snapd/snapshots/5_obs-studio_27.1.3_1284.zip`. Still, I think this is very much unwanted behavior. I think the right coarse of action is to make a PR to obs that adds a new ENV var that would let us change that directory. And then set that directory to the localized version of `$HOME/Video`.

**Comment by timthelion** [comment]
I started a discussion here: https://github.com/obsproject/obs-studio/discussions/5896
